name: Install and test fpm in a git workflow

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    
    - name: Install fpm
      run: |
        sudo apt-get install ruby ruby-dev rubygems build-essential
        sudo gem install --no-document fpm

    - name: Test fpm
      run: |
        fpm --version
