name: Install and test fpm in a git workflow

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    
    - name: Checkout
      uses: actions/checkout@v2

    - name: Fix world writable dirs
      run: |
        chmod go-w $HOME
        sudo chmod -R go-w /home/linuxbrew
        sudo chmod -R go-w /home/runner
        sudo chmod -R go-w /usr/share
        sudo chmod -R go-w /opt
          
    - name: Setup ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6

    - name: Install fpm
      run: |
        sudo apt-get install ruby ruby-dev rubygems build-essential
        sudo gem install --no-document fpm

    - name: Test fpm
      run: |
        /usr/local/bin/fpm -s dir -t pacman -n test --force --prefix /opt/pack --chdir pack
